# Generated by Django 4.1.2 on 2022-10-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtasks',
            name='description',
            field=models.CharField(default='new_task', max_length=500),
        ),
        migrations.AddField(
            model_name='sharedtasks',
            name='title',
            field=models.CharField(default='new', max_length=100),
        ),
    ]
