# Generated by Django 4.1.2 on 2022-10-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_sharedtasks_description_sharedtasks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtasks',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
