# Generated by Django 4.0.8 on 2022-10-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_sharedtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='is_completd',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
    ]
