# Generated by Django 4.0.8 on 2022-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_tasks_is_completd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='is_completd',
            field=models.BooleanField(default=False),
        ),
    ]
