# Generated by Django 4.0.8 on 2022-10-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_tasks_is_completd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtasks',
            name='assigned_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
